# Generated by Django 4.2.5 on 2023-09-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sgbvreport',
            name='report_id',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
