# Generated by Django 4.2.5 on 2023-09-21 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_sgbvreport_report_id_alter_sgbvreport_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media_files/')),
            ],
        ),
        migrations.AddField(
            model_name='sgbvreport',
            name='media_files',
            field=models.ManyToManyField(blank=True, to='core.mediafile'),
        ),
    ]
