# Generated by Django 4.2.5 on 2023-09-22 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mediafile_sgbvreport_media_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sgbvreport',
            name='media_files',
        ),
        migrations.DeleteModel(
            name='MediaFile',
        ),
    ]
