# Generated by Django 4.2.5 on 2023-09-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SURVIVOR', 'Survivor'), ('LEGAL', 'Legal Counsel'), ('HEALTH', 'Health Expert')], default='ADMIN', max_length=50),
        ),
    ]
