# Generated by Django 4.2.5 on 2023-09-25 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_1', models.BooleanField(default=False)),
                ('step_2', models.BooleanField(default=False)),
                ('step_3', models.BooleanField(default=False)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.sgbvreport')),
            ],
        ),
    ]
