# Generated by Django 4.2.5 on 2023-09-26 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='sgbvreport',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
    ]
